services:
  influxdb:
    image: influxdb:${INFLUX_VERSION}
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb:/var/lib/influxdb2

  mosquitto:
    image: eclipse-mosquitto:${MOSQUITTO_VERSION}
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/mosquitto/certs

  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    container_name: telegraf
    restart: unless-stopped
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - MQTT_USER=${TELEGRAF_MQTT_USER}
      - MQTT_PASSWORD=${TELEGRAF_MQTT_PASSWORD}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - '8125:8125'

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana-server
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource,pr0ps-trackmap-panel
      - INFLUX_TOKEN=${INFLUX_TOKEN}            # Disponible para datasource de Grafana
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/logs:/var/log/grafana

  image-store:
    build: ./image-store
    container_name: image-store
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - ./images:/app/images

